In [104]:
from collections import OrderedDict
from bokeh.charts import output_file
from bokeh.palettes import Spectral11
from bokeh.plotting import figure, show

from bokeh.sampledata.iris import flowers
from bokeh.charts import Scatter

import numpy as np
import pandas as pd
import tables
import urllib.request

In [111]:
f = urllib.request.urlopen('http://research.rods.pitt.edu/data.csv')
file = f.read()
chartdata = pd.read_csv(file)
chartdata

OSError: Expected file path name or file-like object, got <class 'bytes'> type

In [87]:
chartdata = chartdata[chartdata['Infection_state'] == 'NEWLY_SICK']
chartdata = chartdata.groupby(['Day'])['Count'].aggregate(sum)
chartdata = chartdata.to_frame("Count")
chartdata = chartdata.reset_index()
chartdata

     Day  Count
0      0      0
1      1      0
2      2    192
3      3    233
4      4    257
5      5    279
6      6    304
7      7    329
8      8    359
9      9    390
10    10    422
11    11    460
12    12    499
13    13    542
14    14    588
15    15    640
16    16    694
17    17    752
18    18    814
19    19    885
20    20    958
21    21   1039
22    22   1125
23    23   1219
24    24   1319
25    25   1427
26    26   1540
27    27   1663
28    28   1795
29    29   1934
..   ...    ...
120  120    795
121  121    754
122  122    716
123  123    676
124  124    641
125  125    608
126  126    577
127  127    545
128  128    515
129  129    489
130  130    461
131  131    438
132  132    414
133  133    390
134  134    370
135  135    348
136  136    330
137  137    311
138  138    294
139  139    277
140  140    263
141  141    249
142  142    234
143  143    222
144  144    207
145  145    196
146  146    184
147  147    175
148  148    165
149  149    156

[150 rows x 2 columns]

In [88]:
p = Scatter(chartdata, x='Day', y='Count',
            title="Newly Sick Per Day", legend="top_left",
            xlabel="Day", ylabel="Newly Sick")

output_file("nspd.html")

show(p)

In [89]:
chartdata = data_df[data_df['Infection_state'] == 'NEWLY_SICK']
chartdata = chartdata.groupby(['Day', 'Sex'])['Count'].aggregate(sum)
chartdata = chartdata.to_frame("Count")
chartdata = chartdata.reset_index()
chartdata

     Day Sex  Count
0      0   F      0
1      0   M      0
2      1   F      0
3      1   M      0
4      2   F    131
5      2   M     61
6      3   F    164
7      3   M     69
8      4   F    182
9      4   M     75
10     5   F    199
11     5   M     80
12     6   F    220
13     6   M     84
14     7   F    239
15     7   M     90
16     8   F    262
17     8   M     97
18     9   F    288
19     9   M    102
20    10   F    313
21    10   M    109
22    11   F    343
23    11   M    117
24    12   F    374
25    12   M    125
26    13   F    409
27    13   M    133
28    14   F    447
29    14   M    141
..   ...  ..    ...
270  135   F     23
271  135   M    325
272  136   F     21
273  136   M    309
274  137   F     19
275  137   M    292
276  138   F     17
277  138   M    277
278  139   F     15
279  139   M    262
280  140   F     14
281  140   M    249
282  141   F     13
283  141   M    236
284  142   F     12
285  142   M    222
286  143   F     12
287  143   M    210
288  144   F      9
289  144   M    198
290  145   F      8
291  145   M    188
292  146   F      7
293  146   M    177
294  147   F      7
295  147   M    168
296  148   F      7
297  148   M    158
298  149   F      6
299  149   M    150

[300 rows x 3 columns]

In [90]:
p = Scatter(chartdata, x='Day', y='Count', color='Sex',
            title="Newly Sick per Day by Sex", legend="top_left",
            xlabel="Day", ylabel="Newly Sick")

output_file("nspdbs.html")

show(p)

/Users/jdl50/anaconda/lib/python3.5/site-packages/bokeh/charts/_attributes.py:78: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort(columns=columns)

In [91]:
chartdata = data_df[data_df['Infection_state'] == 'NEWLY_SICK']
chartdata = chartdata.groupby(['Day', 'Sex','Location_level_2'])['Count'].aggregate(sum)
chartdata = chartdata.to_frame("Count")
chartdata = chartdata.reset_index()
chartdata = chartdata[chartdata.Sex.str.contains("M") == False]
chartdata

     Day Sex Location_level_2  Count
0      0   F           State1      0
1      0   F           State2      0
2      0   F           State3      0
6      1   F           State1      0
7      1   F           State2      0
8      1   F           State3      0
12     2   F           State1    131
13     2   F           State2      0
14     2   F           State3      0
18     3   F           State1    164
19     3   F           State2      0
20     3   F           State3      0
24     4   F           State1    182
25     4   F           State2      0
26     4   F           State3      0
30     5   F           State1    199
31     5   F           State2      0
32     5   F           State3      0
36     6   F           State1    220
37     6   F           State2      0
38     6   F           State3      0
42     7   F           State1    239
43     7   F           State2      0
44     7   F           State3      0
48     8   F           State1    262
49     8   F           State2      0
50     8   F           State3      0
54     9   F           State1    288
55     9   F           State2      0
56     9   F           State3      0
..   ...  ..              ...    ...
840  140   F           State1     14
841  140   F           State2      0
842  140   F           State3      0
846  141   F           State1     13
847  141   F           State2      0
848  141   F           State3      0
852  142   F           State1     12
853  142   F           State2      0
854  142   F           State3      0
858  143   F           State1     12
859  143   F           State2      0
860  143   F           State3      0
864  144   F           State1      9
865  144   F           State2      0
866  144   F           State3      0
870  145   F           State1      8
871  145   F           State2      0
872  145   F           State3      0
876  146   F           State1      7
877  146   F           State2      0
878  146   F           State3      0
882  147   F           State1      7
883  147   F           State2      0
884  147   F           State3      0
888  148   F           State1      7
889  148   F           State2      0
890  148   F           State3      0
894  149   F           State1      6
895  149   F           State2      0
896  149   F           State3      0

[450 rows x 4 columns]

In [92]:
p = Scatter(chartdata, x='Day', y='Count', color='Location_level_2',
            title="Newly Sick per Day by Sex by State", legend="top_left",
            xlabel="Day", ylabel="Newly Sick")

output_file("nspdbs.html")

show(p)

/Users/jdl50/anaconda/lib/python3.5/site-packages/bokeh/charts/_attributes.py:78: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort(columns=columns)

In [93]:
chartdata = data_df[data_df['Infection_state'] == 'NEWLY_SICK']
chartdata = chartdata.groupby(['Day', 'Sex','Location_level_2',"Location_level_3"])['Count'].aggregate(sum)
chartdata = chartdata.to_frame("Count")
chartdata = chartdata.reset_index()
chartdata = chartdata[chartdata.Sex.str.contains("M") == False]
chartdata = chartdata[chartdata.Location_level_2.str.contains("State2") == False]
chartdata = chartdata[chartdata.Location_level_2.str.contains("State3") == False]

chartdata

      Day Sex Location_level_2 Location_level_3  Count
0       0   F           State1          County1      0
1       0   F           State1          County2      0
2       0   F           State1          County3      0
18      1   F           State1          County1      0
19      1   F           State1          County2      0
20      1   F           State1          County3      0
36      2   F           State1          County1     37
37      2   F           State1          County2      7
38      2   F           State1          County3     87
54      3   F           State1          County1     46
55      3   F           State1          County2      8
56      3   F           State1          County3    110
72      4   F           State1          County1     51
73      4   F           State1          County2      9
74      4   F           State1          County3    122
90      5   F           State1          County1     56
91      5   F           State1          County2     10
92      5   F           State1          County3    133
108     6   F           State1          County1     62
109     6   F           State1          County2     12
110     6   F           State1          County3    146
126     7   F           State1          County1     67
127     7   F           State1          County2     12
128     7   F           State1          County3    160
144     8   F           State1          County1     74
145     8   F           State1          County2     13
146     8   F           State1          County3    175
162     9   F           State1          County1     81
163     9   F           State1          County2     15
164     9   F           State1          County3    192
...   ...  ..              ...              ...    ...
2520  140   F           State1          County1      2
2521  140   F           State1          County2      4
2522  140   F           State1          County3      8
2538  141   F           State1          County1      2
2539  141   F           State1          County2      3
2540  141   F           State1          County3      8
2556  142   F           State1          County1      2
2557  142   F           State1          County2      3
2558  142   F           State1          County3      7
2574  143   F           State1          County1      2
2575  143   F           State1          County2      3
2576  143   F           State1          County3      7
2592  144   F           State1          County1      1
2593  144   F           State1          County2      3
2594  144   F           State1          County3      5
2610  145   F           State1          County1      1
2611  145   F           State1          County2      2
2612  145   F           State1          County3      5
2628  146   F           State1          County1      1
2629  146   F           State1          County2      2
2630  146   F           State1          County3      4
2646  147   F           State1          County1      1
2647  147   F           State1          County2      2
2648  147   F           State1          County3      4
2664  148   F           State1          County1      1
2665  148   F           State1          County2      2
2666  148   F           State1          County3      4
2682  149   F           State1          County1      1
2683  149   F           State1          County2      2
2684  149   F           State1          County3      3

[450 rows x 5 columns]

In [94]:
p = Scatter(chartdata, x='Day', y='Count', color='Location_level_3',
            title="Newly Sick Females per Day by Counties in State 1", legend="top_left",
            xlabel="Day", ylabel="Newly Sick")

output_file("nspdbs.html")

show(p)

/Users/jdl50/anaconda/lib/python3.5/site-packages/bokeh/charts/_attributes.py:78: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  df = df.sort(columns=columns)